owner: unosquare # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: ClientCore
    url: http://clientcore.unosquare.com/
  - name: TimeCore
    url: https://timecore.unosquare.com/
  - name: Exec Reports
    url: http://reports.unosquare.com/
  - name: Interviews
    url: https://interviews.unosquare.com/
  - name: Core API Health
    url: https://unocoreapi.azurewebsites.net/health
  - name: Core ELP API Health
    url: https://elpapi.azurewebsites.net/health
  - name: Core Client API Health
    url: https://clietcore.azurewebsites.net/health
  - name: Core API Staging Health
    url: https://unocoreapistaging.azurewebsites.net/health
  - name: Core ELP API Staging Health
    url: https://elpstaging.azurewebsites.net/health
  - name: Core Client API Staging Health
    url: https://clientstaging.azurewebsites.net/health
  - name: Core AI API Staging Health
    url: https://coreaistaging.azurewebsites.net/health

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Unosquare Upptime
  introTitle: "Unosquare Website and APIs status page."
  introMessage: You can report issues to Production Support.
  navbar:
    - title: Status
      href: /
    
workflowSchedule:
  uptime: "*/15 * * * *"
