owner: unosquare
repo: upptime

sites:
  - name: Core
    url: $CORE_API_PATH
  - name: ELP
    url: $ELP_API_PATH
  - name: Vacations
    url: $VACATIONS_API_PATH
  - name: Forms
    url: $FORMS_API_PATH
  - name: AI
    url: $AI_API_PATH
  - name: Workflow
    url: $WORKFLOW_API_PATH
  - name: Auth
    url: $AUTH_API_PATH
  - name: Reports
    url: $REPORTS_API_PATH
  - name: Billing
    url: $BILLING_API_PATH
  - name: Graph
    url: $GRAPH_API_PATH
  
assignees: # Users to assign downtime issues (optional)
  - jpalcala
  - clementezazueta
status-website:
  publish: true
  theme: ocean
  faviconSvg: https://unosquare.github.io/cdn.unosquare.com/assets/icons/unicorn_icon.svg
  favicon: https://www.unosquare.com/wp-content/uploads/2025/01/cropped-unosquare-favicon-192x192.png
  logoUrl: https://unosquare.github.io/cdn.unosquare.com/assets/icons/unicorn_icon.svg
  cname: status.unosquare.com # Custom domain CNAME
  name: Unosquare
  navbar:
    - title: Status
      href: /
    - title: Report an issue
      href: https://unosquare.atlassian.net/servicedesk/customer/portal/2/create/19
workflowSchedule:
  uptime: "*/10 8-20 * * 1-5"
